app/App.vue
app/env.d.ts
app/lib/auth.ts
app/lib/compositions.ts
app/lib/helper.ts
app/lib/index.ts
app/lib/network.ts
app/package-lock.json
app/package.json
app/views/user/loginView.vue

思いつける機能を載せましたが、
何か足りないか教えてください。
見た目は未実装のまま

feat: :sparkles: ログインViewの機能実装

---

app/lib/compositions.ts
app/views/user/signUpView.vue

feat: :sparkles: サインアップViewの機能実装

---

web/app/index.css
web/app/postcss.config.js
web/app/tailwind.config.js

公式ドキュメント通りにやったら公式の想定してるディレクトリ構成と今回のディレクトリ構成に差異がありその影響でtailwindを読み込むファイルのパスの指定が間違っていたのを修正しました。

fix:TailwindCSSの設定が間違っていてCSSが読み込めてなかった問題を修正

---

web/app/plugin/router.ts

開発中は大丈夫が、プロダクションになったらバグるっていうワーニングが出てます

fix: :bug: ルーターのimportを修正

---

.github/workflows/docker-build-test.yml
web/Dockerfile

フロントの `Dockerfile` をPRするたびにビルドする
ビルド失敗したらPRはマージできないはず

ci: :construction_worker: Dockerfileを試行buildするCIを作成

---

README.md
docker-compose.yml

back側でdbのヘルスチェックを行い、mysqlが立ち上がったら接続するようにしました。
参考：https://blog.mtb-production.info/entry/2021/09/18/204107

初回起動時、DBの作成完了前にDjangoが接続して起こるエラーを解消

---

web/app/App.vue
web/app/component/GlobalHeader/Link.vue
web/app/component/GlobalHeader/Main.vue
web/app/component/modal/friend.vue
web/app/main.ts
web/app/package-lock.json
web/app/package.json
web/app/plugin/index.ts
web/app/plugin/router.ts
web/app/plugin/vuex.ts
web/app/views/brain/createView.vue

フレンドのモーダル（形だけ）実装。
サイドメニューのフレンドの欄をクリックするとフレンドリストが表示されるようにした。
フレンドリストの表示切替の実装に伴いvuexを導入

Feat friend modal

---

web/app/App.vue
web/app/component/GlobalHeader/Main.vue
web/app/dummy/brain.ts
web/app/plugin/router.ts
web/app/views/brain/createView.vue

Back updated

---

web/app/component/brain/BrainStatusBox.vue
web/app/dummy/brain.ts
web/app/views/brain/listView.vue

fix:API不使用版プレゼン前最終調整

---

back/app/apiv1/serializers.py
back/app/apiv1/urls.py
back/app/apiv1/views.py
back/app/memore/admin.py
back/app/memore/models.py

共有機能で修正が必要だったので、models.py の一部を変更しました。
変更後のデータ設計

add: フレンド共有とノート共有を実装するにあたりmodels.py の修正変更

---

back/app/apiv1/serializers.py
back/app/apiv1/urls.py
back/app/apiv1/views.py

URLパラメータとjwtの認証情報を使ってログインユーザを判別できるように修正

change: 各エンドポイントのパラメータを変更修正

---

back/app/accounts/serializers.py

この[issue](https://github.com/Kazumasa1/memo-re/issues/126)の対応PRです。

パスワードをハッシュ化＆レスポンスでパスワードを返さないように変更

---

back/app/accounts/views.py

change: auth/users/me/ でemailとpasswordを変更できないよう変更

---

back/app/apiv1/urls.py
back/app/apiv1/views.py

Feature/#122  friend note list

---

back/app/accounts/serializers.py
back/app/apiv1/views.py

change: ユーザ検索APIのレスポンスボディを修正

---

back/app/apiv1/views.py

Feature/#127  updata note share

---

back/app/apiv1/views.py

add: ノート共有でフレンドチェックを追加

---

back/app/apiv1/views.py

以下の点を追加しました。
- フレンドのノートを共有申請できるように修正
- パラメータで渡された項目をチェックする処理を追加
チェック項目を views.py に書いてしまっているので、後からバリデーションに移行します・・・
とりあえず、フロントと結合したいのでPRします。

Feature/#196  change note share

---

back/app/apiv1/urls.py
back/app/apiv1/views.py

add: 他ユーザからのノート共有申請の一覧取得を追加

---

back/app/apiv1/serializers.py
back/app/apiv1/views.py

#208 の対応PRです。
レスポンスボディが以下のように変更されました。
```
[
{
"user_from": 1,
"username": "adminname",
"icon_uri": "http://localhost:8000/media/icon/default.png",
"tag": null,
"notified": true,
"register_at": "2023-01-24T23:25:44+09:00",
"apply": false,
"rejection": false
},
{
"user_from": 5,
"username": "yakiniku",
"icon_uri": "http://localhost:8000/media/icon/IMG_5446.JPG",
"tag": null,
"notified": true,
"register_at": "2023-01-25T00:11:39+09:00",
"apply": false,
"rejection": false
}
]
```

add: 他ユーザからのフレンド申請一覧のパラメータの修正

---

back/app/apiv1/serializers.py
back/app/apiv1/urls.py
back/app/apiv1/views.py

add: 全てのユーザの公開ノートを一覧取得するAPIを追加

---

back/app/apiv1/urls.py
back/app/apiv1/views.py

add: フレンドチェック用APIを追加
